### PR TITLE
BUGFIX - validate form fields before submitting

### PR DESCRIPTION
**Pull request by s-barrah**
BUGFIX - validate form fields before submitting

### CODE REVIEW

**Comment by Heleen-cr** [comment]
I think it's a matter of updating the regex patterns we're using and not allow the string to start with a space?

**Comment by Heleen-cr** [comment]
for example for the last name field you can update the json with: `"pattern": "^[A-Za-z0-9][A-Za-z0-9 ,.()\/&\\-']+$",`

**Comment by s-barrah** [comment]
> for example for the last name field you can update the json with: `"pattern": "^[A-Za-z0-9][A-Za-z0-9 ,.()\/&\\-']+$",`
@Heleen-cr 
The postcode issue is on donate and not Giftaid. There is no problem with the last name field. What is happening on Giftaid is that some forms are getting submitted with empty address line 1 and postcode fields. I have added a validation to ensure the form doesn't submit unless these fields are not empty.

**Comment by s-barrah** [comment]
> I think it's a matter of updating the regex patterns we're using and not allow the string to start with a space? We'll need to update the postcodelookup in storybook. At the same time we can update the postcode field to turn off autocomplete.

The postcode issue is on donate so we either need the same validation we did on here on donate or update storybook.

**Comment by Heleen-cr** [comment]
Ok yeah that's one way of doing it. 
Though I think we need to look at the source of the issue.
I think the main problem lies in the regex for the address fields in the postcode lookup and we should fix it there as this is also an issue on Donate. 

The postcode problem mentioned above is indeed on donate, since donate hasn't been updated to the latest postcode fixes in storybook. 

Also are you sure there's no issue with the last name field? ;)

**Comment by s-barrah** [comment]
> Ok yeah that's one way of doing it.
> Though I think we need to look at the source of the issue.
> I think the main problem lies in the regex for the address fields in the postcode lookup and we should fix it there as this is also an issue on Donate.
> 
> The postcode problem mentioned above is indeed on donate, since donate hasn't been updated to the latest postcode fixes in storybook.
> 
> Also are you sure there's no issue with the last name field? ;)

The currently problem is that we have forms submitting with empty values for `address1` and `postcode`. I have added a fix to prevent the form from submitting if any of the required fields are empty. I am currently updating storybook autocomplete property for input fields and also a security issue with `shelljs`

**Pull request closed without merging**
