### PR TITLE
fix: Update dependencies

### PR DESCRIPTION
**Pull request by AndyEPhipps**
Addressing a number of higher and critical level dependency updates.

### CODE REVIEW

**Comment by AndyEPhipps** [comment]
@KrupaPammi are you able to confirm the Nightwatch updates run happily with the update? I tried locally but it looks like there's missing config or something, perhaps it's never setup to run locally, only on the suitable envs?

                                                                                         │
```
│    [Update/Sorry] Test Suite                                                              │
│    ──────────────────────────────────────────────────                                     │
│    - Connecting to hub-cloud.browserstack.com on port 443...                              │
│    ⚠ Failed to connect to Selenium Server on hub-cloud.browserstack.com with port 443.    │
│    See more info, video, & screenshots on Browserstack:                                   │
│      https://automate.browserstack.com/builds/undefined/sessions/undefined
```

**Comment by KrupaPammi** [comment]
Will check @AndyEPhipps

**Comment by KrupaPammi** [comment]
Hi @AndyEPhipps sorry took a while to fix the tests, had trouble with my wifi at home from morning. Tests are passing foe me locally with these updates.

**Review by KrupaPammi — APPROVED** [review]

**Comment by AndyEPhipps** [comment]
No probs at all, thanks @KrupaPammi

**Pull request merged**
