### PR TITLE
Add tooltip to Update form

### PR DESCRIPTION
**Pull request by AndyEPhipps**
As per https://comicrelief.atlassian.net/browse/ENG-2603

New functionality visible here: https://deploy-preview-397--giftaid-react.netlify.app/update

### CODE REVIEW

**Review by pauldolden — APPROVED** [review]
This looks fine to me. Though I do believe the transaction ID is at the bottom of the email.

**Comment by AndyEPhipps** [comment]
> This looks fine to me. Though I do believe the transaction ID is at the bottom of the email.

Ah, will check in with Andrew/an email template

**Comment by AndyEPhipps** [comment]
For the papertrail, Paul was indeed right, so any changes to that would need to be updated here https://github.com/comicrelief/serverless-mailer/blob/2531148ebf42f255c41b889d149c6e244e68b969/src/Template/General/Donate/Success.html.ejs#L33

**Review by pauldolden — APPROVED** [review]
🥇

**Pull request merged**
