### PR TITLE
Update copy for big night in

### LINKED ISSUE #235: Update Gift Aid declaration - Big Night In
Gift aid your donation and the Government will give 25% on top of it. This will be split 50/50 between Comic Relief and BBC Children in Need as per your donation.

Yes, I would like BBC Children in Need and Comic Relief to claim Gift Aid on my donation. *

### PR DESCRIPTION
**Pull request by lebaz20**
Fixes #235

### CODE REVIEW

**Comment by adamclark-dev** [comment]
@lebaz20 we need to make it so that it detects the site and switches the text, we don't want to do this for all of our journeys

**Comment by lebaz20** [comment]
@adamclark-dev ah ok, what is the condition to display this copy ?

**Comment by adamclark-dev** [comment]
use the site service and site config file, might be worth adding the text to the site config file. text changes will only be if site = bignightin

**Comment by lebaz20** [comment]
ok, understood, working on it!

**Pull request merged**
