### PR TITLE
Email with long value is slowing down and crashing

### LINKED ISSUE #250: Email with long value is slowing down and crashing
if an email consists of a length which is more 13-15 chars before or after `@` is slowing down and then crashing.

### PR DESCRIPTION
**Pull request by LouiaR**
fixes #250

### CODE REVIEW

**Comment by LouiaR** [comment]
@KrupaPammi  can you QA this when you are free

**Comment by KrupaPammi** [comment]
Tested the fix @LouiaR, looks good, just found couple of issues mentioned below:

1.  Email that starts with a space is not giving an error message, atm it's allowing spaces to be entered before the start of the address which should display an error message.

2. Emails that have double quotes before @ is giving an error message but that doesn't do for any other special character except for this, can we allow " to be accepted?  like this `"email"@example.com`

**Comment by KrupaPammi** [comment]
> Tested the fix @LouiaR, looks good, just found couple of issues mentioned below:
> 
> 1. Email that starts with a space is not giving an error message, atm it's allowing spaces to be entered before the start of the address which should display an error message.
> 2. Emails that have double quotes before @ is giving an error message but that doesn't do for any other special character except for this, can we allow " to be accepted?  like this `"email"@example.com`

**Comment by KrupaPammi** [comment]
> > Tested the fix @LouiaR, looks good, just found couple of issues mentioned below:
> > 
> > 1. Email that starts with a space is not giving an error message, atm it's allowing spaces to be entered before the start of the address which should display an error message.
> > 2. Emails that have double quotes before @ is giving an error message but that doesn't do for any other special character except for this, can we allow " to be accepted?  like this `"email"@example.com`

Discussed with @LouiaR, space is getting ignored on submit, email value is going into the queue as expected. Data contract for email string has the length of 500 so ignoring the issue of length limit.

Passed QA

**Pull request closed without merging**
