### PR TITLE
ENG-2236: MP update

### PR DESCRIPTION
**Pull request by AndyEPhipps**
[ENG-2236](https://comicrelief.atlassian.net/browse/ENG-2236)

[ENG-2236]: https://comicrelief.atlassian.net/browse/ENG-2236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by AndyEPhipps** [comment]
Brings in the update MPs, reordered so the "passing the value behind the scenes" Post and Text options sit nicely underneath the fields with inputs.

**Comment by KrupaPammi** [comment]
Have tested this @AndyEPhipps works as expected.

**Review by KrupaPammi — DISMISSED** [review]

**Comment by KrupaPammi** [comment]
Let me update nightwatch tests that affects this change

**Comment by AndyEPhipps** [comment]
> Let me update nightwatch tests that affects this change

Ah grand, thanks @KrupaPammi 🙌

**Review by KrupaPammi — APPROVED** [review]

**Pull request merged**
