### PR TITLE
Update mobile help text

### PR DESCRIPTION
**Pull request by tomisaacmarshall**
Andrew has requested an update to this text

### CODE REVIEW

**Comment by KrupaPammi** [comment]
@tomisaacmarshall not sure how to test this, do we have a preview env for this?

**Review by AndyEPhipps — APPROVED** [review]

**Comment by AndyEPhipps** [comment]
Given it's just a copy update in config, I'm happy to wave it through

**Review by seb-cr — APPROVED** [review]
Looks fine, although was this copy preferred over simply deleting the word "text"?

Also, does everyone who calls to donate get directed to the giftaid site? Wondering about people who use a landline, since the field label is "mobile number".

**Comment by KrupaPammi** [comment]
yeah happy to merge this in and i'll quickly check on staging

**Comment by tomisaacmarshall** [comment]
> Looks fine, although was this copy preferred over simply deleting the word "text"?
> 
> Also, does everyone who calls to donate get directed to the giftaid site? Wondering about people who use a landline, since the field label is "mobile number".

Yeah text was preferred & I asked Andrew about landlines - he said it's definitely just mobiles

**Comment by KrupaPammi** [comment]
Tested on staging, looks fine.

**Pull request merged**
