### PR TITLE
fix: Use correctly-cased postcode in Nightwatch tests, as per new validation

### PR DESCRIPTION
**Pull request by AndyEPhipps**

### CODE REVIEW

**Comment by AndyEPhipps** [comment]
@KrupaPammi I was seeing Cypress failure tests _locally_ but not on the PR build, which makes me believe 2 different versions are being used.

I've updated the tests to reflect what I believe to be changes to Cypress commands; he [docs](https://docs.cypress.io/api/commands/check) still show the ability to pass a checkbox/radiobutton value in `check()` but it wasn't working locally for me? 🤷).

I've also stipulated a specific Cypress version in package.json, and it's working happily on both builds now.

**Comment by KrupaPammi** [comment]
Ok, thanks for fixing @AndyEPhipps there are some outdated cypress tests there. Will look into it once I'm done with PW tests.

**Comment by AndyEPhipps** [comment]
Thanks @KrupaPammi; are you able to approve this if you're happy?

**Comment by KrupaPammi** [comment]
yeah sorryy for the delay @AndyEPhipps, was running the tests of this branch  in my local, seeing some failures, so was updating them, will push the changes in few mins.

**Comment by AndyEPhipps** [comment]
> yeah, sorry for the delay @AndyEPhipps, I was running the tests of this branch locally, and seeing some failures, so was updating them, will push the changes in a few mins.

Ahh okay, thanks @KrupaPammi; I didn't realise you'd be fixing them here now

**Comment by AndyEPhipps** [comment]
Thanks for the additional fixes @KrupaPammi 🙌

**Comment by KrupaPammi** [comment]
no worries @AndyEPhipps :)

**Pull request merged**
