### PR TITLE
Storybook update with 'autocompleted select' F/E bugfix

### PR DESCRIPTION
**Pull request by AndyEPhipps**
Fixes https://comicrelief.atlassian.net/browse/ENG-1723

(much like the Donate fix, which just a feel styletweaks needed for this app, and also some test updates as this Storybook update also pulls in the relaxed postcode validation we added to the Lookup for CWG)

### CODE REVIEW

**Comment by AndyEPhipps** [comment]
Screen Shot 2022-08-12 at 10 14 26

Screen Shot 2022-08-12 at 10 14 51

Screen Shot 2022-08-12 at 10 14 59

**Comment by KrupaPammi** [comment]
@AndyEPhipps I tested this, country field dropdown icon is not showing when using auto-complete to fill the form but appears when the form is left empty without being filled. Postcode validation is working fine.

**Comment by AndyEPhipps** [comment]
Ohhh that's very weird, let me see why it's not working on the test env..

**Comment by AndyEPhipps** [comment]
Dohhhh, I used a local path to the image 🙄 

I can see it on preview env now, sorry about that!

https://deploy-preview-355--giftaid-react.netlify.app/

**Comment by KrupaPammi** [comment]
No worries, thanks Andy. I can see it working now :)

**Review by KrupaPammi — APPROVED** [review]

**Comment by AndyEPhipps** [comment]
Thanks Krupa!

**Pull request merged**
