### PR TITLE
[ENG-484] Giftaid MP data test

### PR DESCRIPTION
**Pull request by KrupaPammi**

### CODE REVIEW

**Comment by KrupaPammi** [comment]
@AndyEPhipps I'm seeing a sorry page after submitting the form on localhost http://localhost:3000/
I pulled latest master and created this PR. Not sure why it goes to a sorry page. Can you give it a look when you get few mins please? 

Screen Shot 2021-06-10 at 15 57 45

**Comment by KrupaPammi** [comment]
@AndyEPhipps Looks like this dependabot failed too from previous merge https://github.com/comicrelief/giftaid-react/pull/314

**Comment by AndyEPhipps** [comment]
Sure thing @KrupaPammi

**Comment by AndyEPhipps** [comment]
Hm, it's built okay for me; those warnings in the console won't stop a submission. Have you definitely run `yarn`/`npm install`/etc. to make sure you've got up-to-date node modules locally?

**Comment by AndyEPhipps** [comment]
I'm able to submit on the test env too; perhaps your test values are getting rejected by the backend in the submission?

**Comment by AndyEPhipps** [comment]
Re-ran the build, it's working fine now

**Comment by KrupaPammi** [comment]
great, thanks @AndyEPhipps

**Review by AndyEPhipps — APPROVED** [review]

**Pull request merged**
