### PR TITLE
Updates for form submission

### PR DESCRIPTION
**Pull request by AndyEPhipps**
#79

### CODE REVIEW

**Comment by AndyEPhipps** [comment]
The BE has yet to be updated, but we can still complete the journey fine in the FE:

https://deploy-preview-81--giftaid-react.netlify.com/update/ to manually set the transactionID

or https://deploy-preview-81--giftaid-react.netlify.com/update/43243243434324 to pass an transactionID via the url

**Comment by k-pammi** [comment]
Verified, found below issues:
1. Postcode: when I fill in all the required fields and enter the postcode but don't click on 'find address' button and click on ''Update giftaid declaration' button, it's going to the thank you page. 
Expected: it'd be good if we show an error message to select an address.
2. 'read more' button looks too long on success page
3. Transaction ID: If I enter an invalid transation id, I get this error message `This field only accepts alphanumeric characters and ' . - & _` I guess we should update the error message with an appropriate one that is relevant to the transation ID, as the format doesn't take `' . - & _` these characters so we should remove it from the error message.
4.

**Comment by k-pammi** [comment]
I'm still testing this, just adding the issues above so I won't forget them.

**Comment by k-pammi** [comment]
@LaBustaffa as discussed, could you do a design review for this please? Links are on top, in Andy's comment.

**Comment by AndyEPhipps** [comment]
Just listing the fixes as I do 'em; will sort out an env later

1. Postcode validation and error stuff now fixed with new SB version

2. Btn now has auto width on larger breakpoints

3. Hmm, I just looked at adding in a custom error message here, seems we have an issue with the component where passing the custom msg automatically displays it, before it's even running validation. I'd guess we're adding and removing values here upon validation, so setting it out the gate causes an 'error' state. Will need to look into this separately.

4. & 6. Waiting on a decision re: this format and stuff...

5.  'Transaction ID - on https://deploy-preview-81--giftaid-react.netlify.com/update/transID-speacial-char-%22%C2%A3%5E$% url when I type in special characters in the transaction id after /update and refresh, then I get 400 bad request' - given that the URL parameter will be populated by Smartfocus, we shouldn't be accepting any old strings. I'll see if I can make anything like this just forward to the Sorry page.

7 & 9. Fixed with PCLU update

10. This how the normal GA form is styled, and as it's a shared header component; best keep things consistent across this app.

11. Will sort this later this afternoon

**Comment by AndyEPhipps** [comment]
`12. Error message scrolling is not working on IE11 and Edge 17 browsers.
` Hmm, it's working on all IE11s and Edge 17 browsers for me; do you think you can test again once I sort the env?

**Comment by k-pammi** [comment]
> `12. Error message scrolling is not working on IE11 and Edge 17 browsers.` Hmm, it's working on all IE11s and Edge 17 browsers for me; do you think you can test again once I sort the env @k-pammi ?

sure @AndyEPhipps

**Comment by AndyEPhipps** [comment]
`13. Error scrolling is not working on Address 1 and Town fields when we submit the form filling in all the required fields even postcode but without clicking find address button.
`
Have updated logic to include these fields 'hidden' within the PCLU

**Comment by AndyEPhipps** [comment]
1. Will now show erroring address fields when postcode isn't searched for.

2. Changed width on MD and LG breakpoints, still 100% on SM for accessibility and UX

3. TODO: This will require work done on the component itself; currently setting custom error messages shows the error msg by default

4. TODO: needs custom regex to match either the format of:
- GAPS id: D-CJC0494
- or PSL transactionID: D4788C2C-1F61-402D-B4DB-3B4045463803

5. TODO: Low priority as url parameters are only being passed by transaction emails, and it looks like bug has nothing to do with this code, more how create-react-app or netlify deals with special characters in a URL 

6. TODO: can update the pattern, but still have the same issue as (3),

7. Fixed with PCLU updates

8. TODO: will require SB component work, existing bug

9. Fixed with PCLU updates

10. Won't fix, keep same styles as the rest of the GA form

11. Error styles added to these fields

12. Couldn't reproduce across all IE11s and Edge 17

13. Fixed with error scroll updates

**Comment by LaBustaffa** [comment]
- On small breakpoints the postcode component should behave like it does on donation (field and button on the same line)
- The copy " By ticking I state I am a UK taxpayer ... pay any difference." should be support text: in grey and 16 rather than 18
- The copy and headings on the page should be in the normal purple (29022C) rather than black - you can't really tell from the designs, sorry. I need to share them in a different way
- Can we have the button saying 'Update declaration'? (I'm asking mostly @CarolineRennie )

All good otherwise, thanks! :)

**Comment by k-pammi** [comment]
> 1. Will now show erroring address fields when postcode isn't searched for.
> 2. Changed width on MD and LG breakpoints, still 100% on SM for accessibility and UX
> 3. **TODO**: This will require work done on the component itself; currently setting custom error messages shows the error msg by default
> 4. **TODO**: needs custom regex to match either the format of:
> 
> * GAPS id: D-CJC0494
> * or PSL transactionID: D4788C2C-1F61-402D-B4DB-3B4045463803
> 
> 1. **TODO**: Low priority as url parameters are only being passed by transaction emails, and it looks like bug has nothing to do with this code, more how create-react-app or netlify deals with special characters in a URL
> 2. **TODO**: can update the pattern, but still have the same issue as (3),
> 3. Fixed with PCLU updates
> 4. **TODO**: will require SB component work, it's also an existing bug
> 5. Fixed with PCLU updates
> 6. Won't fix, keep same styles as the rest of the GA form
> 7. Error styles added to these fields
> 8. Couldn't reproduce across all IE11s and Edge 17
> 9. Fixed with error scroll updates
> 
> Test env: https://5b9fc7fc792f893e965342d6--giftaid-react.netlify.com/update

1. Fixed
2. Fixed
7. Fixed
9. this is fixed but found another one which is: Enter postcode and all the required fields with valid inputs and click on 'find address' button and select any radio button in 'your giftaid declaration' and click on 'update giftaid declaration' notice no error messages are displayed for address 1 and town fields. Would it possible to show an error message that says: `please select your address or enter your address manually`? 
11. Red outline is still missing on `Email address` field when error message is displayed.
12. Works as expected 
13. Fixed
14. **Town field** - when I enter some text in town field and then give a space and enter a number or forward slash, then it's going to a sorry page. **Expected:** should show an error message

**Comment by k-pammi** [comment]
@AndyEPhipps FYI, regarding issue 4 (error message on postcode) I mentioned in my last comment, I discussed that issue with @deniselashlley yesterday as she is already working on postcode issues and it behaves the same on Donate too. So once it's fixed on storybook, we can pull in those changes for giftaid?

**Comment by AndyEPhipps** [comment]
@k-pammi: yeah, that can be pulled in no problem, if @deniselashlley is already doing the work 👍 

Will look at the outstanding stuff and @LaBustaffa 's style updates today

**Comment by AndyEPhipps** [comment]
> 8.Town field - when I enter some text in town field and then give a space and enter a number or forward slash, then it's going to a sorry page. Expected: should show an error message and not allow to go to a sorry page.

This is due to the BE validation expecting just an alphabetic string; the PCLU fields are set up to accept alphanumeric (inc symbols) values for all fields to suit the different formats used in all countries etc.

Will make sure the BE is updated to allow this

**Comment by AndyEPhipps** [comment]
Okay, so adding the custom error message copy to the Transaction ID will need a bug fixed in the SB component itself. For now, I'm gonna add the regex so it'll match either the following formats:

```
GAPS id: X-XXXXXXX
PSL transactionID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
```

but the error msg will be incorrect.

**Comment by k-pammi** [comment]
> New test env @k-pammi https://5ba23a63b13fb15bfb25c953--giftaid-react.netlify.com/update
> 
> Not sure if you wanna wait till I've sorted the custom error msg thing or not, but it's there if you do

cool, thanks @AndyEPhipps, will pick this up once I finish testing the postcode ticket.

**Comment by AndyEPhipps** [comment]
@k-pammi here's the newest test env: https://5ba367a3b3127465ab8f2023--giftaid-react.netlify.com/update

**Comment by AndyEPhipps** [comment]
@k-pammi fixed! https://5ba38c1e1f12b72c52caa133--giftaid-react.netlify.com/update

**Comment by k-pammi** [comment]
@AndyEPhipps re https://github.com/comicrelief/giftaid-react/pull/81/commits/db12a10c82c4b01e75271611a5ddd12557d77998 for GAPs ID, looking into GiftAidCancels in the DB the first input is always an alphabet even after `-` are always in alphabets and  in Upper case, so could you change the regex for GAPs id to have only ([A-Z]{1}(-)[A-Z0-9]{7}? @corinja could you confirm please?

**Comment by corinja** [comment]
@k-pammi yes, that's correct for GAPS IDs - e.g. D-BEX1501, D-BFA8782 etc

**Comment by AndyEPhipps** [comment]
@corinja also, is that letter-number layout for this GAPS ID always the same as the above? i.e. `L-LLLNNNN` ?

And would there be a similar letter-number pattern for PSL? Just trying to keep as much fake news out of your queues as possible

**Comment by corinja** [comment]
@AndyEPhipps yes, that format L-LLLNNNN is valid for all GAPS ids. The transaction IDs from the PSL are universally unique identifiers (UUID) so they follow the format described here https://en.wikipedia.org/wiki/Universally_unique_identifier

**Comment by AndyEPhipps** [comment]
@k-pammi : new regex stuff here: https://5ba3aee2fdd72a3eebdea494--giftaid-react.netlify.com/update

**Comment by k-pammi** [comment]
> @k-pammi : new regex stuff here: https://5ba3aee2fdd72a3eebdea494--giftaid-react.netlify.com/update

GAPs and PSL id working as expected now

**Comment by AndyEPhipps** [comment]
@k-pammi :
> Town field when London 1 or London / is entered its going to a sorry page.
This is due to the BE returning an error as it's currently only expecting alphabetic characters; we still need to make these BE updates

I've fixed the focus issue here: https://5ba3c191c9659215a27934a2--giftaid-react.netlify.com/update/test

**Comment by k-pammi** [comment]
@AndyEPhipps Focus issue is Fixed on all browsers except IE11 and Edge browsers.

**Comment by k-pammi** [comment]
Accessibility issues:
**Using NVDA on IE11**
1.  On chrome and IE11 browsers 'Accept button' on the cookie message is not highlighted when it's focused using tab key
2. Using tab key on browser address bar is skipping the cookie message section, CR logo and jumps to the Transaction ID field
3. 'Update Declaration' button is not clearly visible when it's tabbed on that button. It shows a slight colour changes when it's focused and not focused but would be good if shows the dotted outline like it does on other buttons.

**Comment by AndyEPhipps** [comment]
IE focus issues fixed here: https://5ba4d00c4ed62f73a9e67130--giftaid-react.netlify.com/update

**Comment by AndyEPhipps** [comment]
Test env: https://5ba4dbef1f12b704899145bd--giftaid-react.netlify.com/update

> 1. On chrome and IE11 browsers 'Accept button' on the cookie message is not highlighted when it's focused using tab key

White buttons didn't have a hover/focus state in the PL, I've added a 

>2. Using tab key on browser address bar is skipping the cookie message section, CR logo and jumps to the Transaction ID field

I wonder if this is something specific to NVDA's settings; these elements are tab-able on every browser I tried, including IE11s on all Windows machines. I've added a `tabindex` to the header logo to try; if that works, we'll have to update the CookieMessage storybook component too I guess.

> 3. 'Update Declaration' button is not clearly visible when it's tabbed on that button. It shows a slight colour changes when it's focused and not focused but would be good if shows the dotted outline like it does on other buttons.

Added to same test env ^

**Comment by k-pammi** [comment]
> Test env: https://5ba4dbef1f12b704899145bd--giftaid-react.netlify.com/update
> 
> > 1. On chrome and IE11 browsers 'Accept button' on the cookie message is not highlighted when it's focused using tab key
> 
> White buttons didn't have a hover/focus state in the PL, I've added a custom one in.
> 
> > 1. Using tab key on browser address bar is skipping the cookie message section, CR logo and jumps to the Transaction ID field
> 
> I wonder if this is something specific to NVDA's settings; these elements are tab-able on every browser I tried, including IE11s on all Windows machines. I've added a `tabindex` to the header logo to try; if that works, we'll have to update the CookieMessage storybook component too I guess.
> 
> > 1. 'Update Declaration' button is not clearly visible when it's tabbed on that button. It shows a slight colour changes when it's focused and not focused but would be good if shows the dotted outline like it does on other buttons.
> 
> Added to same test env ^

@AndyEPhipps fixes for above issues are working as expected now

**Comment by AndyEPhipps** [comment]
@k-pammi - did the logo tab fix work too?

**Comment by k-pammi** [comment]
> @k-pammi - did the logo tab fix work too?

@AndyEPhipps yes, logo tab fix also works as expected.

**Comment by AndyEPhipps** [comment]
Great, I'll add the same fix to the cookie banner in SB and pull that into here now 👍

**Comment by AndyEPhipps** [comment]
@k-pammi error stuff sorted! https://5baa61e782d3f175d520b2d0--giftaid-react.netlify.com/

**Comment by k-pammi** [comment]
@AndyEPhipps re PCLU - when I fill in all the required fields with valid input and enter the postcode then **don't** click on 'find address' button and submit the form.  "Please fill in your address"  is not displayed.

**Comment by AndyEPhipps** [comment]
@k-pammi : is that on the main GA form or /update?

**Comment by k-pammi** [comment]
@AndyEPhipps yeah, seems to work fine now. 
Tested PCLU updates, works as expected. Just found issues with tab
1. When I leave all the fields blank and submit the form, then when I enter inputs in each field, when I come to last name field and enter an input there and then tab/not tab, the cursor immediately moves to postcode field skipping the email field. This happens only when the form is submitted with an error on all 3 forms.
2. On https://5baa61e782d3f175d520b2d0--giftaid-react.netlify.com/ when I fill in all the required fields leaving Address1 and Town fields and submit the form, then when i'm trying to type `Address` in Address 1 field, as soon I finish typing the 3rd character, then the cursor jumps to Town field and fills in the rest of the characters I was typing in Address 1 field.
3. On https://5baa61e782d3f175d520b2d0--giftaid-react.netlify.com/ JIT link needs to be aligned to centre below 'Gift aid declaration' button. (sorry I had no clarity about the forms and though we are replacing https://5baa61e782d3f175d520b2d0--giftaid-react.netlify.com/ with /update form and that's why I hadn't tested it before. I will check the form with mobile number field now and see if it's working as expected)

**Comment by AndyEPhipps** [comment]
@k-pammi : Both journeys (https://5bb33e40b3127420677f8c06--giftaid-react.netlify.com/ and https://5bb33e40b3127420677f8c06--giftaid-react.netlify.com/update) can be re-QA'ed now

Browserstack is being super slow for me (maybe my crummy home internet), but I've checked and this all works fine for me W7 IE11, Win10 Edge 17, most recent iOS and Android, plus my local Chrome obviously.

**Comment by k-pammi** [comment]
@AndyEPhipps Verified the above fixes, they work as expected now.

**Comment by AndyEPhipps** [comment]
Great, thanks for all the retesting @k-pammi! I'll get Denise to code review this tomorrow and we can merge it in (staging deploy is still paused) to get this PR done, and will put in a new PR for that work required after BE and Data work is complete.

**Comment by k-pammi** [comment]
no worries, thanks @AndyEPhipps

**Comment by k-pammi** [comment]
@AndyEPhipps Can we get this merge on staging so I can do e2e testing?

**Comment by AndyEPhipps** [comment]
Ooh yes, I'll unpause deployment now

**Pull request merged**
